export const planets = [
  { id: '1', name: 'Tatooine' },
  { id: '2', name: 'Alderaan' },
  { id: '3', name: 'Yavin IV' },
  { id: '4', name: 'Hoth' },
  { id: '5', name: 'Dagobah' },
  { id: '6', name: 'Bespin' },
  { id: '7', name: 'Endor' },
  { id: '8', name: 'Naboo' },
  { id: '9', name: 'Coruscant' },
  { id: '10', name: 'Kamino' },
  { id: '11', name: 'Geonosis' },
  { id: '12', name: 'Utapau' },
  { id: '13', name: 'Mustafar' },
  { id: '14', name: 'Kashyyyk' },
  { id: '15', name: 'Polis Massa' },
  { id: '16', name: 'Mygeeto' },
  { id: '17', name: 'Felucia' },
  { id: '18', name: 'Cato Neimoidia' },
  { id: '19', name: 'Saleucami' },
  { id: '20', name: 'Stewjon' },
  { id: '21', name: 'Eriadu' },
  { id: '22', name: 'Corellia' },
  { id: '23', name: 'Rodia' },
  { id: '24', name: 'Nal Hutta' },
  { id: '25', name: 'Dantooine' },
  { id: '26', name: 'Bestine IV' },
  { id: '27', name: 'Ord Mantell' },
  { id: '28', name: 'unknown' },
  { id: '29', name: 'Trandosha' },
  { id: '30', name: 'Socorro' },
  { id: '31', name: 'Mon Cala' },
  { id: '32', name: 'Chandrila' },
  { id: '33', name: 'Sullust' },
  { id: '34', name: 'Toydaria' },
  { id: '35', name: 'Malastare' },
  { id: '36', name: 'Dathomir' },
  { id: '37', name: 'Ryloth' },
  { id: '38', name: 'Aleen Minor' },
  { id: '39', name: 'Vulpter' },
  { id: '40', name: 'Troiken' },
  { id: '41', name: 'Tund' },
  { id: '42', name: 'Haruun Kal' },
  { id: '43', name: 'Cerea' },
  { id: '44', name: 'Gleen Anselm' },
  { id: '45', name: 'Iridonia' },
  { id: '46', name: 'Tholoth' },
  { id: '47', name: 'Iktotch' },
  { id: '48', name: 'Quermia' },
  { id: '49', name: 'Dorin' },
  { id: '50', name: 'Champala' },
  { id: '51', name: 'Mirial' },
  { id: '52', name: 'Serenno' },
  { id: '53', name: 'Concord Dawn' },
  { id: '54', name: 'Zolan' },
  { id: '55', name: 'Ojom' },
  { id: '56', name: 'Shako' },
  { id: '57', name: 'Muunilinst' },
  { id: '58', name: 'Shili' },
  { id: '59', name: 'Kalee' },
  { id: '60', name: 'Umbara' },
]